{% set name = "larray-editor" %}
{% set version = "0.29" %}
{% set sha256 = "5945651408848150ca436ba1abecddc0a0a573e34640a089ca29f27c90cfaffe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1

requirements:
  host:
    - pip
    - python
    - setuptools
    - larray
    - pytest-runner

  run:
    - python
    - larray
    - matplotlib
    - pyqt
    - qtpy
    - pytest-runner

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Graphical User Interface for LArray."

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
