{% set version = "0.34.1" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: b6c62fcf003c014b8c30ee95f09a490becd2557f92bdff45c5a3bfcee2158272

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    # it is indirectly pulled from larray, but let us be explicit about this
    - numpy
    - matplotlib
    - pyqt >=5
    - qtpy >=2    # for Qt6 support
    # jedi >=0.18 to workaround incompatibility between jedi <0.18 and parso >=0.8 (see #220)
    - jedi >=0.18
    - qtconsole !=5.4.2

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
