{% set name = "larray-editor" %}
{% set version = "0.28" %}
{% set sha256 = "712220f244fb7b703f36ecb53c0cc093c9943ea0e4481864d1d12fe26f7ce601" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - larray
    - pytest-runner

  run:
    - python
    - larray
    - matplotlib
    - pyqt
    - qtpy
    - pytest-runner

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Graphical User Interface for LArray."

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
