{% set version = "0.33.1" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: 56dc00825735664a82518a6dab7b1df17c5cf6c4792b023f4c700bfadb04c3e6

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    - matplotlib
    - pyqt >=4.6  # for API v2
    - qtpy

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Graphical User Interface for LArray
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
