{% set version = "0.32.2" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: 1354893feff80b0bc62f4841e76fdead7b04b5616d2d411737ff0244ce5dc8a3

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    - matplotlib
    - pyqt >=4.6  # for API v2
    - qtpy

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
