{% set version = "0.30" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: dc67ee46509ba94ed35f3b2e1ba35642f9e1f6d9161b1abda3fad83cd5d30855

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
    - larray
    - pytest-runner
  run:
    - python
    - larray
    - matplotlib
    - pyqt
    - qtpy
    - pytest-runner

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
