{% set version = "0.34.6" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: c68f08aebd7c04896c2f2b583f8d9cd3ca53cac1baf480525ce107f4b3c07d7c

build:
  noarch: python
  number: 2
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    # it is indirectly pulled from larray, but let us be explicit about this
    - numpy
    - matplotlib
    - pyqt >=5
    - qtpy >=2    # for Qt6 support
    # jedi >=0.18 to workaround incompatibility between jedi <0.18 and parso >=0.8 (see #220)
    - jedi >=0.18
    - qtconsole !=5.4.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
