{% set version = "0.29" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: f0fbe767a3c186f42177c5753817dbf7bcd7eee7abe31f4b0765f8f8f3f82faa

build:
  noarch: python
  number: 1

requirements:
  host:
    - python
    - pip
    - larray
    - pytest-runner
  run:
    - python
    - larray
    - matplotlib
    - pyqt
    - qtpy
    - pytest-runner

test:
  imports:
    - larray_editor

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
