# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OO4/z5luHI47+F162VoaT/DOcNm8siBHBvm1ONNS4y3YD5i4g2yFpaI4jTO3uSkFzFqUj3PyXlu1moL0Nx4ArSJ2d174+Pa8y2vsMzb5AugnrBKT+e3Y8thOm5wqe6cWKy7R0G9hNdWqCZUqMkX9sj0kkQrLnTon+MyiGitIDD34APzp8MZecL6RpSTaVlzInIcG8VgoPrX+heBuemag8p6UM3ytHyr9jc+0dg6F3K2Xq3b1tMLhq48AITHgdV6LRRWErNZzIe8C0DSsuKQOU8qr3v1nIwaZYqVcW1XS53/lGimqv06LF2KV9JAig240ze3N1Lfv2vYENSFbBkyhyH0lUpE9BLDQHqC5hTWl3hM2ZMU7QQYOwI45qMC3yYrGL5Wx8lFI5loNtPCjr8IeMVYgdyDzXkzgekHZT6yrNFsac6kVdfGfPLdEP74iWLs/TyCY6Xa+Nj/Igq64hN7GSn/bNOhPSdzWaxeF8LfrvQ8N679SlvbSC1jyXnGXSNwnwq05Ylss+AeTkiOx4XPZ6r4hEJShKNf7Nfu7b/8Nl2n34W+9+ZJSTiAic3A+phP8eDjJFQL3X+yas+FWeOwJBq+e6OGqlYqiJ+g1i4ExL6rwyKkeIoCfxdyC9PurGYkTSSpaL8pNBAyZv/g6nY1/YNKJdpwTmpqJE58iKK5unAg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
