travis:
  secure:
    BINSTAR_TOKEN: OO4/z5luHI47+F162VoaT/DOcNm8siBHBvm1ONNS4y3YD5i4g2yFpaI4jTO3uSkFzFqUj3PyXlu1moL0Nx4ArSJ2d174+Pa8y2vsMzb5AugnrBKT+e3Y8thOm5wqe6cWKy7R0G9hNdWqCZUqMkX9sj0kkQrLnTon+MyiGitIDD34APzp8MZecL6RpSTaVlzInIcG8VgoPrX+heBuemag8p6UM3ytHyr9jc+0dg6F3K2Xq3b1tMLhq48AITHgdV6LRRWErNZzIe8C0DSsuKQOU8qr3v1nIwaZYqVcW1XS53/lGimqv06LF2KV9JAig240ze3N1Lfv2vYENSFbBkyhyH0lUpE9BLDQHqC5hTWl3hM2ZMU7QQYOwI45qMC3yYrGL5Wx8lFI5loNtPCjr8IeMVYgdyDzXkzgekHZT6yrNFsac6kVdfGfPLdEP74iWLs/TyCY6Xa+Nj/Igq64hN7GSn/bNOhPSdzWaxeF8LfrvQ8N679SlvbSC1jyXnGXSNwnwq05Ylss+AeTkiOx4XPZ6r4hEJShKNf7Nfu7b/8Nl2n34W+9+ZJSTiAic3A+phP8eDjJFQL3X+yas+FWeOwJBq+e6OGqlYqiJ+g1i4ExL6rwyKkeIoCfxdyC9PurGYkTSSpaL8pNBAyZv/g6nY1/YNKJdpwTmpqJE58iKK5unAg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
