travis:
  secure:
    BINSTAR_TOKEN: SrlQRdyVOyIXOpdM660eZ/1KQoMtiyEhzkplyfDNLn45uiGBRy5v80Ot3SwJ4dlILK8WZGHqswNCHj9kBa0BUUHNikyXYzUsVdpYFKwK5n9nIeOb6v9CxfNDGyq3o78KGY27N9cqjRRqiUS2o1/UVuxBz4pL0P3nNRfruyV3DsDcqVXTWLURDwdjJNoGSsQ2sNAuep9bmNX9hYzMRhA7/vpaf9eXTJ10Pwg8i3iCeFlYkUCa32f43yACbFo3RORlATJi/wEnQaqld3bWQ6GiaITOVJj7SA9j3IAHHXAvaYNg0slSFpmJW3xztmXj3WrBEP3m0M0rfb4uiHTbATtNTXh++w13LUn+fepsDdL0NT25xMfchygkUMA6PVE41VoABRW69HLYYFn9IKckQ2XMwWSbJt8aCN/hfsBUBWxcTEzY9+cr12hoZdFIkF7CsHFpxnatpNV39DSvRDqtQNo52AKYHcSfQacnBmWmRSZXNWPOWnV0FG0Ywg97kTC3C1MJx2LrPjOrIgpndj0zA9z3rZdffMr6iubsXlkh5fiC8BYLXz+OB11fbmSGIXekoQijjCdDA5OjlmvEPCA4C34eIo7/D205ne6lIWixwzXyS7lyiEmt2BT6ZhUEqt14gR4jFvbUKNcRB5MStWIVo7r6Rqbk8w7cLesjKZmn9ipeTXM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
